Repository tenoxui/tenoxui, pull requests merged in 2024-05, with the labels that each got.

#16 docs: update README file ✨
  README.md
Labels: documentation

#18 docs: update README file
  README.md
Labels: documentation, enhancement

#19 v0.9.0-alpha.7 code
  CHANGELOG.md
  package.json
  src/css/tenoxui.css
  src/js/lib/color.d.ts
  src/js/lib/color.js
  src/js/lib/color.js.map
  src/js/lib/property.d.ts
  src/js/lib/property.js
  src/js/lib/property.js.map
  src/js/lib/props.d.ts
  src/js/lib/props.js
  src/js/lib/props.js.map
  src/js/tenoxui.d.ts
  src/js/tenoxui.esm.d.ts
  src/js/tenoxui.esm.js
  src/js/tenoxui.esm.js.map
  src/js/tenoxui.js
  src/js/tenoxui.js.map
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
Labels: enhancement, release

#21 TenoxUI v0.10.0 here!
  CHANGELOG.md
  README.md
  package.json
  src/js/tenoxui.d.ts
  src/js/tenoxui.esm.d.ts
  src/js/tenoxui.esm.js
  src/js/tenoxui.esm.js.map
  src/js/tenoxui.js
  src/js/tenoxui.js.map
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
  test/responsiveStyles.test.js
Labels: documentation, dependencies, release

#22 feat: hover effect and responsive styles
  CHANGELOG.md
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
  test/valueValidator.test.js
Labels: enhancement

#24 tenoxui/css v0.10.0-alpha.2 code
  CHANGELOG.md
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
Labels: enhancement, release

#26 Fix: camelcase properties not working properly
  .prettierrc
  CHANGELOG.md
  package.json
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
  tsup.config.ts
Labels: bug, documentation, dependencies, release

#27 Pre-release v0.10 code
  CHANGELOG.md
  package.json
  src/js/tenoxui.d.ts
  src/js/tenoxui.esm.d.ts
  src/js/tenoxui.esm.js
  src/js/tenoxui.esm.js.map
  src/js/tenoxui.js
  src/js/tenoxui.js.map
  src/ts/tenoxui.esm.ts
  src/ts/tenoxui.ts
Labels: documentation, enhancement, dependencies, release
